# Basic Numpy Arrays

In [ ]:
import sys
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([1,1.2,3,4.5,5])

In [ ]:
a[0],a[1]                                             # Prints (np.int64(1), np.int64(2))
a[0:]                                                 # Prints array([1, 2, 3, 4, 5])
a[1:3]                                                # Prints array([ 2, 3])
a[1:-1]                                               # Prints array([2, 3, 4])
a[[0,2,-1]]                                           # Prints array([1, 3, 5])

array([1, 3, 5])

In [ ]:
b                                           # Prints array([1. , 1.2, 3. , 4.5, 5. ])
b[0],b[-1],b[2]                             # Prints (np.float64(1.0), np.float64(5.0), np.float64(3.0))
b[[0,2,-1]]


array([1., 3., 5.])



---


# Array Types

In [ ]:
a                                             # Prints array([1, 2, 3, 4, 5])
b                                             # Prints array([1. , 1.2, 3. , 4.5, 5. ])
a.dtype                                       # Prints dtype('int64')
b.dtype                                       # Prints dtype('float64')

dtype('float64')

In [ ]:
np.array([1,2,3,4], dtype = np.float128)                           # Prints array([1., 2., 3., 4.], dtype=float128)
np.array([1.,3.,4.34352662,7.6,4.2],dtype = np.int32)              # Prints array([1, 3, 4, 7, 4], dtype=int32)

array([1, 3, 4, 7, 4], dtype=int32)

In [ ]:
c = np.array(['a','b','c'])
c.dtype

dtype('<U1')

In [ ]:
d = np.array([{'a':1},sys])
d                        # Prints (array([{'a': 1}]
d.dtype                  # Prints dtype('O'))

(array([{'a': 1}, <module 'sys' (built-in)>], dtype=object), dtype('O'))



---


# Dimensions and Shapes

In [ ]:
A = np.array([
              [1,2,3,4],
              [5,6,7,8]
              ])
print(A)                                     # Print(A) or A

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
A.shape                                  # Prints (2, 4) i.e 2 Rows and 4 Coloumns
A.ndim                                   # Prints 2 i,e 2 dimensions
A.size                                   # Prints 8 i.e Total 8 elements are there

8

In [ ]:
B = np.array([[
    [1,2,3,4,5],
    [6,7,8,9,10]
],[
    [11,12,13,14,15],
    [16,17,18,19,20]
              ]])

In [ ]:
B
B.shape                        # Prints (2, 2, 5)
B.ndim                         # Prints 3 i,e 3 dimensions
B.size                         # Prints 20 i.e Total 20 elements are there

20



---


# Indexing and Slicing of Matrices

In [ ]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
A
A.shape                                      # Prints (3,3)
A.size                                       # prints 9
A[1]                                         # prints array([4, 5, 6])
A[0][2].item()                               # Prints 3 i.e item() - returns the element instead of along with the data type
A[0,2]                                       # Above can be written like this too - Prints 3
A[1:]                                        # Prints array([[4, 5, 6],
                                                          # [7, 8, 9]])
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
A[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
A[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
A[2:,1:]

array([[8, 9]])

In [ ]:
A[1] = np.array([10,10,10])
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
A[2] = np.array([20,20,20])
A[2] = 20                         # Does the same job as above
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [20, 20, 20]])

In [ ]:
A[1,2] = 35                                   # Row 1 & Coloumn 2
A

array([[ 1,  2,  3],
       [10, 10, 35],
       [20, 20, 20]])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 35],
       [20, 20, 20]])



---
# Summary statistics


In [ ]:
z = np.array([1,2,3,4])
z.sum().item()                          # Prints 10
z.mean().item()                         # Prints 2.5
z.std().item()                          # Prints 1.118033988749895

1.118033988749895

In [ ]:
A.sum(axis=0)                            # Performs the coloumn wise operation - Prints array([31, 32, 58])
A.sum(axis=1)                            # Performs the Row wise operation     - Prints array([ 6, 55, 60])
A.mean(axis=0)                           # Performs the Coloumn wise operation - prints array([10.33333333, 10.66666667, 19.33333333])
A.mean(axis=1)                           # Performs the Row wise operation     - prints array([ 2.        , 18.33333333, 20.        ]

array([ 2.        , 18.33333333, 20.        ])

In [ ]:
f = np.arange(4)                                     # Creats the array of given size - Prints array([0, 1, 2, 3])
f + 10                                               # Can Perform arithmetic functions to the complete array - Prints array([10, 11, 12, 13])
f - 10                                               # Can Perform arithmetic functions to the complete array - Prints array([-10,  -9,  -8,  -7])
f * 10                                               # Can Perform arithmetic functions to the complete array - Prints array([ 0, 10, 20, 30])
f * 10                                               # Can Perform arithmetic functions to the complete array - Prints array([ 0, 10, 20, 30])
f / 10                                               # Can Perform arithmetic functions to the complete array - Prints array([0. , 0.1, 0.2, 0.3])
f += 100                                             # Can Perform arithmetic functions to the complete array - Prints array([100, 101, 102, 103])
[i.item() * 10 for i in f]                           # Prints [1000, 1010, 1020, 1030]

[1000, 1010, 1020, 1030]

In [ ]:
a = np.arange(4)
b = np.arange(4)

In [ ]:
a + b
a * b

array([0, 1, 4, 9])



---

# Boolean arrays

In [ ]:
c = np.arange(4)
c >= 2                                                # Prints array([False, False,  True,  True])
c[c <= 2]                                             # Prints array([0, 1, 2])

array([0, 1, 2])

In [ ]:
D = np.random.randint(100)                           # np.random.randint(100): This generates random integers between 0 and 99 (since 100 is exclusive).

68

In [ ]:
D = np.random.randint(100, size = (3,3))             # Generates random 3*3 array
D

array([[98, 83, 75],
       [86, 70, 12],
       [82, 65,  7]])

In [ ]:
D[D >= 35]

array([98, 83, 75, 86, 70, 82, 65])



---

# Size of objects in Memory


In [ ]:
# An integer in Python is > 24bytes
sys.getsizeof(1)                                   # Prints 28
# Longs are even larger
sys.getsizeof(10**100)                             # Prints 72
# Numpy size is much smaller
np.dtype(int).itemsize                             # Prints 7
# Numpy size is much smaller
np.dtype(np.int8).itemsize                         # Prints 1
# A one-element list
sys.getsizeof([1])                                 # Prints 64

64



---


# Useful Numpy functions

In [ ]:

np.random.randint(100, size = 2)

array([89, 54])

In [ ]:
np.random.normal(size=2)

array([-0.02555938, -1.11328924])

In [ ]:
np.arange(10)
np.arange(5,10)                              # Creats the array from 5 to 9 i.e array([5, 6, 7, 8, 9])
np.arange(7,78)                              # Creates the array from 7 to 77
np.arange(2,20,2)                            # Satrting from 2 and By stepping 2 elements it prints array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.arange(5,10,.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
np.linspace(0, 1, 5)                       # If you want 5 points between 0 and 1
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.identity(3)                           # It creates a 3x3 identity matrix.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3)                               # It creates a 3x3 identity matrix.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
"Hello World"[6]

'W'